### ISSUE TITLE
I am can not change "I want.." in "Search preference"

### ISSUE THREAD

**Issue by parom2020** [Alovoa/alovoa-expo#40]
Hi!
I am a new user this app. Version 1.8.2. Downloaded from f-droid.
Before i set variable "I want.." in "Search preference" to "Relationship". Yesterday changed to "To meet new people". Now i want change back. But list to set this variable is not active. I can not change variable "I want.."!
This bug in Android and Web version. See screenshots. 

Best, regards Parom

![Screenshot 2024-03-02 at 14-33-33 Search preferences](https://github.com/Alovoa/alovoa-expo/assets/71543557/4bd6cc8d-d580-41e1-8121-4ebc9d14070f)
![photo_2024-03-02_14-22-09](https://github.com/Alovoa/alovoa-expo/assets/71543557/490381b2-6ae3-462c-995a-668730ab32ff)
![photo_2024-03-02_14-22-03](https://github.com/Alovoa/alovoa-expo/assets/71543557/be0724b8-061b-41b9-82a4-94232f07571d)

**Comment by Nonononoki** [comment]
There's a cooldown of 24 hours, try again later
