### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Alovoa/alovoa-expo#5]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4581114988#L2337 (maybe related to https://github.com/Alovoa/alovoa-expo/issues/4?) 

Anyway, let me remove that line...

```
+ cd android/app
+ gradle assembleRelease
Found 7.5.1 via distributionUrl
Downloading missing gradle version 7.5.1
cachedir
/tmp/tmp.I297vkj0qf/gradle-7.5.1-bin.zip: OK
Running /opt/gradle/versions/7.5.1/bin/gradle assembleRelease

Welcome to Gradle 7.5.1!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5.1/release-notes.html

To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.5.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 

FAILURE: Build failed with an exception.

* Where:
Script '/home/vagrant/build/com.alovoa.expo/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 450

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /home/vagrant/build/com.alovoa.expo/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.
```

Hmm, now?

/LE: fyi, https://gitlab.com/fdroid/fdroiddata/-/commit/fe29469fcc263a3e481bfb2d1de16ad4d7987633

**Comment by Nonononoki** [comment]
@licaon-kter The first build error seems to be because I removed the react-native-get-location library, which it cannot find anymore.
The second more obscure error seems to be a rare issue, which can be resolved by just doing a gradle clean? Never seen that before, but found some info on stackoverflow: https://stackoverflow.com/questions/57744141/react-native-build-error-unable-to-determine-the-current-character-it-is-not-a

**Comment by licaon-kter** [comment]
We are doing a gradle clean after `prebuild:` yes

**Comment by Nonononoki** [comment]
Then I have no clue, maybe you can restart the build and see if the error happens again?

**Comment by licaon-kter** [comment]
Replaced the scanignore, build fine: https://gitlab.com/fdroid/fdroiddata/-/commit/1eea6c17300a949f0e7ae87a4f3b69fa2b10f842

**Comment by Nonononoki** [comment]
Does this mean the build always breaks whenever I remove a dependency?

**Comment by licaon-kter** [comment]
Now you've removed one and added another.

But yes, if those need to be in the scanignore list, that needs to be updated.
