### ISSUE TITLE
Download .apk from github directly with Obtainium

### ISSUE THREAD

**Issue by HomemadeAdvanced** [Alovoa/alovoa-expo#51]
I would like to pull the latest .apk directly from github using Obtainium. In order to do this, the latest released .apk would have to be listed under Releases. Would this be possible or is there another way to get the latest .apk directly without using F-Droid? Thanks in advance.

**Comment by Nonononoki** [comment]
What's wrong with F-droid?

**Comment by HomemadeAdvanced** [comment]
In the past I have read some articles about it e.g. https://privsec.dev/posts/android/f-droid-security-issues/

**Comment by Nonononoki** [comment]
In my opinion, it's safe enough. There's also a Google Playstore version, apk can be downloaded via Aurora Store.

**Comment by HomemadeAdvanced** [comment]
I know, but then F-Droid is better. If it is not planned, feel free to close the issue.
