### ISSUE TITLE
[BUG] Attempted registration gives errors

### ISSUE THREAD

**Issue by ooooooooooooooooooooooooooooooooooooooh** [Alovoa/alovoa-expo#55]
**Check if you're in the correct repository**

The bug appears on `app.alovoa.com` as well as in the Android app.

**Describe the bug**

Trying to create a new account in the Android app by clicking "sign up with email" gives the message "an error occurred. Please try again.".

After the registration didn't work I switched to the website so I can get some helpful debug logs. The `POST https://beta.alovoa.com/register` logs the following with error code 409:

```
POST
https://beta.alovoa.com/register
[HTTP/2 409  2124ms]

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

could not execute statement [(conn=17975) Field &#39;number_profile_views&#39; doesn&#39;t have a default value] [insert into user (accent_color,admin,audio_id,confirmed,country,dates_id,delete_token_id,description,disabled,email,first_name,gender_id,intention_id,language,location_latitude,location_longitude,number_referred,number_searches,password,password_token_id,prefered_max_age,prefered_min_age,profile_picture_id,referrer_code,register_token_id,show_zodiac,total_donations,ui_design,units,user_settings_id,uuid,verification_code,verification_picture_id) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)]
```

Also note that I used `app.alovoa.com` and never specified anything about using `beta` APIs. Not sure if this is intended behavior.

Aside from that, there are several error logs before that (again, not sure if this is intended behavior):

- `BackHandler is not supported on web and should not be used.`
- `Uncaught (in promise) DOMException: The operation is insecure.` in [web-cb334e1b8bcca7f8fbc0b0cd2daeff91.js:1469](https://app.alovoa.com/bundles/web-cb334e1b8bcca7f8fbc0b0cd2daeff91.js)
- `Uncaught (in promise) DOMException: The operation is insecure.` in [web-cb334e1b8bcca7f8fbc0b0cd2daeff91.js:1469](https://app.alovoa.com/bundles/web-cb334e1b8bcca7f8fbc0b0cd2daeff91.js)

**To Reproduce**

I used Firefox without any plugins.

0. Clear cookies etc.
1. Go to the app or website "https://app.alovoa.com"
2. Click on 'Sign up with email'
3. Fill all required fields, press register

**Expected behavior**

I expected to registration to work, either redirecting to the login screen or to the actual app.

**Native Application:**

 - 1.9.1, F-Droid

**Web application**

 - Firefox, 123.0

---

Please let me know if you need more information or help.

---

Edit: Also tried it on Chromium 123.0.6312.86 and the POST request fails with the same message. Interestingly, the two other error logs changed:

- `BackHandler is not supported on web and should not be used.`
- `Uncaught (in promise) DOMException: screen.orientation.lock() is not available on this device.` in [web-cb334e1b8bcca7f8fbc0b0cd2daeff91.js:163](https://app.alovoa.com/bundles/web-cb334e1b8bcca7f8fbc0b0cd2daeff91.js)
- `Uncaught (in promise) DOMException: screen.orientation.lock() is not available on this device.` in [web-cb334e1b8bcca7f8fbc0b0cd2daeff91.js:163](https://app.alovoa.com/bundles/web-cb334e1b8bcca7f8fbc0b0cd2daeff91.js)

I hope this helps (if even somehow related).

**Comment by Nonononoki** [comment]
The problem was an unused database column, which I deleted. Could you try again?

**Comment by Nonononoki** [comment]
Thanks for the report! Registration works now :)
