### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by borrougagnou** [Alovoa/alovoa-expo#6]
Hello, I don't understand why,
multiple times when I click on someone who liked me (or same the profile picture)
the app crash...
I don't really understand why.

Also when I press ❤️ to someone, it didn't work.
I need to use the webbrowser to be able to do that.

Regards.

---
Android version: 12
App version: 1.4.0

**Comment by Nonononoki** [comment]
I can only reproduce the crash in the chat screen, let's see if other users face the same issue

**Comment by Nonononoki** [comment]
Should be fixed with Version 1.4.1
