### ISSUE TITLE
Error when creating a profile. 

### ISSUE THREAD

**Issue by TekNicholas** [Alovoa/alovoa-expo#65]
I seem to be getting an error when trying to finish the creation of my profile on app.alovoa.com. I've tried different selections and text in the various fields prior to pushing the "Let's Go" button with no luck. The right arrow in the bottom right of the screen does nothing when pushed on the final screen.

I also attempted it in the android app as well and get the same results when clicking the "Let's Go" button, and the app crashes immediately if I hit the right arrow in the bottom right of the screen. 

** Device (please complete the following information):**
 - OS: 6.5.13-7-MANJARO (64-bit)

**Web application**
 - Browser: Firefox 124.0.1 (64-bit) - no extensions.

Screenshot of the error.
![Screenshot_20240410_231856](https://github.com/Alovoa/alovoa-expo/assets/20053601/00842456-09c5-4a90-963b-f339c7ab2fa2)

**Comment by Nonononoki** [comment]
Should be fixed now: 1f4e0b37dd97b408d15b52d9fad2786cee40ce35
