### ISSUE TITLE
[BUG] app.alovoa.com is down

### ISSUE THREAD

**Issue by Veraellyunjie** [Alovoa/alovoa-expo#72]
app.alovoa.com is down:
```
Proxy Error
The proxy server could not handle the request

Reason: Error during SSL Handshake with remote server

Apache/2.4.57 (Debian) Server at app.alovoa.com Port 443
```

alovoa.com is fine

**Comment by Nonononoki** [comment]
Thanks! Looks like the server ran out of RAM, as both app.alovoa and beta.app.alovoa went down at the same time. Fortunately only the web app was affected. Restarted the web servers and added another 4GB of swap to the system.
