### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by apeixinho** [Alovoa/alovoa-expo#73]
When logging in with username and password, user can't get past captcha. "An error occurred. Try again later"

Follow login procedure, with email and password 

Upon correct captcha, user is able to login

Issue is present in webapp and Android app

**Comment by MxRemy** [comment]
Same issue here, installed from F-Droid, v1.11.0, on GrapheneOS, on a Pixel 7 Pro.

I put in my credentials, the captcha appears, I solve it, and it just returns me to the login screen. If I try again the same thing just keeps occurring.
