### ISSUE TITLE
[FEATURE] when hovering with the mouse over the icons, it should pop up a description of what these mean 

### ISSUE THREAD

**Issue by wiki-me** [Alovoa/alovoa-expo#75]
**Is your feature request related to a problem? Please describe.**

It is unclear what some of the icons mean in the profile page.

**Describe the solution you'd like**
when hovering with the mouse over the icons, it should pop up a description of what these mean. basically something like [this](https://stackoverflow.com/questions/68477072/popup-when-hover-on-text) .

**Describe alternatives you've considered**

none

**Additional context**

picture to help understand:

![Screenshot_20240713_205255](https://github.com/user-attachments/assets/b2baf8a6-6bf4-4c1c-b4a1-695039adf91c)

**Comment by Nonononoki** [comment]
Added to 2.0 release. The icons mean amount donated, number of blocks by users and number of reported by users.

**Comment by Nonononoki** [comment]
Implemented with daf971f6c498818df4eb538e434b828efce0d448, will be live once 2.0 is released.
