### ISSUE TITLE
[BUG] Many repeated profile photos on front page -> use AI generated images instead

### ISSUE THREAD

**Issue by rugk** [Alovoa/alovoa-expo#76]
**Check if you're in the correct repository**

> This repository only covers bugs of app.alovoa.com and iOS/Android apps only. Go to [alovoa](https://github.com/Alovoa/alovoa) for reporting bugs on app.alovoa.com and the backend.

Uhm? The description mentions the same domain twice, and also I found no repo for the landing page aka without the `app.` subdomain, so I hope I am right. If not, feel free to just move the issue.

**Describe the bug**
When going to https://alovoa.com/ for the first time, you are greeted by "avatars"/profile pictures. Which is okay for such an app, but the issue is, many of them.

![grafik](https://github.com/user-attachments/assets/782cf773-ef36-4b41-a913-c15c88637c32)

**To Reproduce**
Just visit https://alovoa.com/

**Expected behavior**
As the first-time experience is important for such an app, and marketing people will likely tell you a bad UX here would be a big hurt for any conversation rate, it should really be not have such a basic flaw… :upside_down_face: 
It makes it look like none is there and the (hopefully artificial!) pictures of the same and the same users would (possibly subconsciously) tell you that you'll likely see the same people again and again there… :wink: 

The easiest solution I'd have in mind (that also works with copyright and privacy laws etc.) is just to use AI generated images. https://www.whichfaceisreal.com/ and https://generated.photos/ have free images to download.

**Screenshots**
see above

** Device (please complete the following information):**
 - OS: Linux
 - OS version: Fedora 40´

**Web application**

 - Browser Firefox
 - Browser version: 128

**Additional context**

**Comment by Nonononoki** [comment]
Wrong repo, this is for app.alovoa.com.
Submit the issue here: https://github.com/Alovoa/alovoa/issues

**Comment by rugk** [comment]
You can move issues between repos AFAIK on GitHub. In the sidebar there should be a small link.

Otherwise I can for sure copy/paste it.
