### ISSUE TITLE
[BUG] alovoa not respecting search preferences , showing me people that want relationships and "sexual intimacy" despite wanting only to meet new people

### ISSUE THREAD

**Issue by wiki-me** [Alovoa/alovoa-expo#77]
**Describe the bug**

alovoa not respecting search preferences , showing me people that want relationships and "sexual intimacy" despite wanting only to meet new people.

**To Reproduce**

Go to search preferences , set "i want" to "to meet new people".

**Expected behavior**

the only people shown are the ones where on the profile it says "to meet new people" and not "sexual intimacy" or "A relationship".

**Screenshots**

![Screenshot_20240727_211355](https://github.com/user-attachments/assets/f5456126-bd24-4947-8f28-6ea92404bd84)

** Device (please complete the following information):**

Debian linux 12

**Web application**

Firefox 115.13.0 esr

**Comment by Nonononoki** [comment]
It's actually not a bug, I decided to not include this setting as a hard criteria until I implement more advanced search filters, as the userbase is still very small.

**Comment by wiki-me** [comment]
If that is the case then at least there should be some indication this is happening.

With that said it feels like a breach of privacy, i am getting profiles of women looking for sex when i am just someone looking to chat, at some point some lady had a picture of her BDSM equipment ...

Even someones co worker finding out they are looking for a relationship and writing information they would not like to broadcast to the world might be a bad experience. This should really be a hard criteria unless it is configured not to be (for example by listing multiple goals like wanting a relationship and people to chat with).

**Comment by wiki-me** [comment]
I have a super nerdy profile with a picture of cat on my profile and someone still made an insinuation about my penis (she was someone looking for "sexual intimacy"). I am a guy and women like that are pretty rare so it doesn't really bother me but women are probably experiencing worst things (with men documented passion toward sending dick pics and things of that sort).

**Comment by Qyd0ro** [comment]
I'm very sorry that has happened to you, @wiki-me 😞 that's very concerning. I hope @Nonononoki will treat the situation seriously and act accordingly asap

**Comment by Qyd0ro** [comment]
> If that is the case then at least there should be some indication this is happening.
> 
> With that said it feels like a breach of privacy, i am getting profiles of women looking for sex when i am just someone looking to chat, at some point some lady had a picture of her BDSM equipment ...
> 
> Even someones co worker finding out they are looking for a relationship and writing information they would not like to broadcast to the world might be a bad experience. This should really be a hard criteria unless it is configured not to be (for example by listing multiple goals like wanting a relationship and people to chat with).

I also couldn't agree more with this. Definitely feels like a breach of privacy: albeit I understand the want to boost the userbase, nonetheless it's very bad software philosophy.

**Comment by wiki-me** [comment]
> I'm very sorry that has happened to you, @wiki-me 😞 that's very concerning. I hope @Nonononoki will treat the situation seriously and act accordingly asap

Its fine, no big deal, I really appreciate Nonononoki for developing this but unforetunatly generally speaking open source developers don't seem to be really interested in developing a open source dating website.  open source comes without warrenty (that's what basically every license says) and i don't think he should start stressing over this. If people really want a really great open source dating website they should fund work on it.

With that i think this might a problem of "male centered design" you sometimes read about . getting feedback about this and maybe even the website itself on a place like [TwoXChromosomes](https://old.reddit.com/r/TwoXChromosomes/) might be good. I am not blaming him, it also toke for me a while to learn for example how common is sexual assualt among women.

**Comment by Qyd0ro** [comment]
I do not know about the community you mention, personally I work with queer activists in the context of _**intersectional**_ feminism, but _governance_ should never be an alien concept both in the OSS and the F/LOSS movements. It is very important to have open corversations about things and move accordingly. The contexts in which we operate are important: if they don't adapt we are called to action for ourselves 🙂
