### ISSUE TITLE
[Android] [Feature Request] Themed / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [Alovoa/alovoa-expo#8]
[https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#User_Theming](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#User_Theming)

**Comment by Nonononoki** [comment]
Could you adjust the link? It links to this github page

**Comment by sebastien46** [comment]
Done.

**Comment by Nonononoki** [comment]
As far as I can tell, you can already theme the icon. Only monochrome app icon is missing. Is this correct?

**Comment by sebastien46** [comment]
Indeed, could that be implemented?

**Comment by Nonononoki** [comment]
Yes, and will probably be included in the next release :)

**Comment by sebastien46** [comment]
I see you've implemented it in [f35432c](https://github.com/Alovoa/alovoa-expo/commit/f35432c63a95d077865fb86047025f840eb7c16b).
Thank you and have a nice day.
