### ISSUE TITLE
[BUG] Compliment prevents profile from being Hidden

### ISSUE THREAD

**Issue by latebeer** [Alovoa/alovoa-expo#83]
If a person sends a 'compliment' with their Like, then on their Profile, the action to 'Hide' that profile is disabled.  Blocking might be appropriate to respond to bots, but not to a courteous person.

**Expected behavior**

I expect to always be able to pass on a profile.

** Device: **
 - OS: Android
 - OS version 13
 - Device: Samsung SM-A515U1

**Native Application:**

 - Version 1.12.0
 - Origin Google Play Store

**Comment by Nonononoki** [comment]
A compliment is equivalent to a like, and you either pass on someone or like someone.
